package com.example.Main.Controllers;


import com.example.Main.Repo.UserRepository;



import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.test.annotation.Commit;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
public class LoginController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Commit
    @PostMapping(path="/login")
    public @ResponseBody
    void getUser(@RequestParam String login, @RequestParam String password) {
        JSONObject obj  = userRepository.findByLogin(login).toJSON();
        String inPassword = obj.get("password").toString();
        if(inPassword.matches(password)){
            System.out.println("You win");
            System.out.println(inPassword + " Vs " + password);
        }
        else {
            System.out.println("Invalid Password");
            System.out.println(inPassword + " Vs " + password);
        }
    }
}